document.addEventListener('DOMContentLoaded', (event) => {
  document.getElementById('downloadBtn').addEventListener('click', () => {
    chrome.tabs.query({active: true, currentWindow: true}, (tabs) => {
      const activeTab = tabs[0];
      chrome.cookies.getAll({url: activeTab.url}, (cookies) => {
        let cookiesOutput = '';

        cookiesOutput +='# Netscape HTTP Cookie File\n';
        cookiesOutput +='# http://curl.haxx.se/rfc/cookie_spec.html\n';
        cookiesOutput +='# This file was generated by Peter Cookie Download\n';
        cookies.forEach((cookie) => {
          cookiesOutput += `${cookie.domain}\t${cookie.hostOnly ? 'FALSE' : 'TRUE'}\t${cookie.path}\t${cookie.secure ? 'TRUE' : 'FALSE'}\t${Math.floor(cookie.expirationDate) || 0}\t${cookie.name}\t${cookie.value}\n`;
        });
        downloadAsFile(cookiesOutput, 'cookies.txt', 'text/plain');
      });
    });
  });

  function downloadAsFile(text, filename, contentType) {
    const a = document.createElement('a');
    const file = new Blob([text], {type: contentType});
    a.href = URL.createObjectURL(file);
    a.download = filename;
    a.click();
  }
});
